const Images = {
	philippines: './img/philippines.jpg',
	india: './img/india.jpg',
	japan: './img/japann.jpg',
	uae: './img/uae.jpg',
	hongkong: './img/hongkong.jpg',
	singapore: './img/singapore.jpg',
	indo: './img/indo.jpg',
	china: './img/china.jpg',
	thailand: './img/thailand.jpg',
	cambodia: './img/cambodia.jpg',
	vietnam: './img/vietnam.jpg',
	malaysia: './img/malaysia.jpg',
	korea: './img/korea.jpg',
	australia: './img/australia.jpg',
	macau: './img/macau.jpg',
	maldives: './img/maldives.jpeg',
	newzealand: './img/newzealand.jpg',
	laos: './img/laos.jpg',
	iceland: './img/iceland.jpg',
	myanmmar: './img/myanmmar.jpg',
	brunie: './img/brunie.jpg',
	taiwan: './img/taiwan.jpg',
	bgHome: './img/bg-home.jpg',
	whatWeDoImg: './img/what-we-do-img.jpg',
	bohol1: './img/bohol-1.jpg', // Philippines
	elnido1: './img/elnido-1.jpg',
	batangas1: './img/batangas-1.jpg',
	palawanElnido: './img/palawan-elnido.jpg',
	palawanPrinsesa: './img/palawan-prinsesa.jpg',
	palawanCoron: './img/palawan-coron.jpg',
	zambalesSubic: './img/zambalesSubic.jpg',
	zambales1: './img/zambales-1.jpg',
	zambales2: './img/zambales-2.jpg',
	cebu1: './img/cebu-1.jpg',
	cebu2: './img/cebu-2.jpg',
	cebu3: './img/cebu-3.jpg',
	agra1: './img/agra-1.jpg', // India
	rajasthan1: './img/rajasthan-1.jpg',
	jammu1: './img/jammu-1.jpg',
	kerala1: './img/kerala-1.jpg',
	himalayas1: './img/himalayas-1.jpg',
	south1: './img/south-1.jpg',
	goa1: './img/goa-1.jpg',
	goa1: './img/goa-1.jpg',
	anadaman1: './img/anadaman-1.jpg',
};

export default Images;
